---
title: "plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

# This page has plotly examples

## scatter plot: 

continous x and y





## violin plot: 
continous y and categorical x



```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

library(plotly)
library(htmlwidgets)
```


## box plot:
continous y and categorical x

```{r}
data("ny_noaa") 
head(ny_noaa)
```


```{r}
noaa_2008_snow = 
ny_noaa %>% 
  drop_na(snow) %>% 
  separate(date, sep="-", into = c("year", "month", "day"), convert = TRUE) %>% 
  filter(
    year == "2008", 
    month == "11",
    snow != "0") %>% 
  mutate(
    day = as.character(day)) %>% 
  select (year, month, day, snow)

head(noaa_2008_snow, 10) 
```

```{r}
plotly_box = 
noaa_2008_snow %>% 
  mutate(day = fct_reorder(day, snow)) %>% 
  plot_ly(
    y = ~snow, x= ~day, color = ~day, type = "box",
    colors = "viridis")
```

## bar plot: 
count y and categorical x

```{r}
data("instacart")
head(instacart)
```
```{r}
ployly_bar = 
  instacart %>% 
  filter(
    aisle == "fresh vegetables"
  ) %>% 
  group_by(order_hour_of_day) %>% 
	count(aisle) %>% 
  arrange(desc(n)) %>% 
  mutate(
    order_hour_of_day = as.character(order_hour_of_day)
  ) %>% 
  plot_ly(
    x = ~order_hour_of_day, y = ~n, color = ~order_hour_of_day, type = "bar", 
    colors = "viridis"
  )
```


## box plot:
continous y and categorical x

```{r}
instacart %>% 
  select(days_since_prior_order, department) %>%
  drop_na(days_since_prior_order)
  plot_ly(
    x = ~department, y = ~days_since_prior_order, color = ~department, type = "box", 
    colors = "viridis"
  )
  
instacart %>% 
  select(aisle, product_name, department) %>% 
  group_by(department) %>% 
  count() %>% 
  arrange(n)
```

